'use strict';
const BRAND={name:'VALORA',logo:{light:{icon:null},dark:{icon:null}}};
const MIN_Z=.03,MAX_Z=20,ZF=1.18;
const PAL=['#10B981','#EF4444','#F59E0B','#3B82F6','#8b5cf6','#0891b2','#db2777','#65a30d','#ea580c','#0f766e'];
const DEF={disponible:'#10B981',libre:'#10B981',vendido:'#EF4444',reservado:'#F59E0B',separado:'#F59E0B',bloqueado:'#94a3b8',contado:'#10B981','financiamiento directo':'#3B82F6',financiamiento:'#3B82F6',directo:'#3B82F6'};
const S={rows:[],rowById:{},svgEl:null,lotMap:{},dims:{w:800,h:600},sc:{},gc:{},gsc:{},cam:{x:0,y:0,z:1,r:0},drag:{on:false},tdist:0,filter:null,exp:new Set(),tab:null,hlEl:null,selLot:null,raf:null,pi:0,user:{name:'Demo',init:'DU'},view:'dash',activity:[],theme:'light',fpCol:false};
let FPD={on:false,ox:0,oy:0};
const $=id=>document.getElementById(id);
const mk=(t,c,x)=>{const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e;};
const nrm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmtP=v=>{const n=parseFloat(String(v).replace(/[^0-9.]/g,''));return isNaN(n)?v:new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',maximumFractionDigits:0}).format(n);};
const fmtL=s=>s.charAt(0).toUpperCase()+s.slice(1).replace(/[_-]/g,' ');
const nextClr=()=>PAL[S.pi++%PAL.length];
const C={id:()=>$('cId')?.value||'',est:()=>$('cEst')?.value||'',pr:()=>$('cPr')?.value||'',sub:()=>$('cSub')?.value||'',pay:()=>$('cPay')?.value||'',payS:()=>$('cPayS')?.value||''};
function valoraSVG(sz,lt){const c1=lt?'#fff':'#1E40AF',c2=lt?'#fff':'#3B82F6';return '<svg viewBox="0 0 64 64" width="'+sz+'" height="'+sz+'" fill="none"><rect x="14" y="14" width="6" height="22" fill="'+c2+'" rx="1"/><rect x="23" y="6" width="6" height="30" fill="'+c1+'" rx="1"/><rect x="32" y="16" width="6" height="20" fill="#10B981" rx="1"/><rect x="41" y="10" width="6" height="26" fill="'+c1+'" rx="1"/><path d="M8 34L32 58L56 34L47 34L32 49L17 34Z" fill="'+c1+'"/></svg>';}
function logoHTML(sz,forDark){const src=BRAND.logo[forDark?'light':'dark']?.icon;return src?'<img src="'+src+'" alt="VALORA" width="'+sz+'" height="'+sz+'" style="display:block;object-fit:contain">':valoraSVG(sz,forDark);}
function initLogos(){[$('lBrandLogo'),$('lCardLogo')].forEach(e=>{if(e)e.innerHTML=logoHTML(24,true);});const nm=$('navMark');if(nm)nm.innerHTML=logoHTML(28,true);const tb=$('tbLogo');if(tb)tb.innerHTML=logoHTML(18,S.theme==='dark');}
function applyTheme(t){S.theme=t;document.body.setAttribute('data-theme',t);try{localStorage.setItem('valora-theme',t);}catch(e){}const btn=$('themeBtn');if(btn)btn.innerHTML=t==='dark'?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="15" height="15"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="15" height="15"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';const tb=$('tbLogo');if(tb)tb.innerHTML=logoHTML(18,t==='dark');}
function toggleTheme(){applyTheme(S.theme==='dark'?'light':'dark');}
function initLoginCards(){const g=$('fcGrid');if(g){g.innerHTML='';for(let i=0;i<35;i++)g.appendChild(mk('div','fc-cell'));const up=()=>{Array.from(g.children).forEach(c=>{c.className='fc-cell';const r=Math.random();if(r<.5)c.classList.add('g');else if(r<.78)c.classList.add('r');else if(r<.9)c.classList.add('a');else if(r<.95)c.classList.add('b');});};up();setInterval(up,2400);}const n=$('fcNum');if(n){let cur=0;const iv=setInterval(()=>{cur+=64;if(cur>=2847){cur=2847;clearInterval(iv);}n.textContent=cur.toLocaleString();},22);}const lv=$('loginView');if(lv){const cards=lv.querySelectorAll('.lfc'),card=lv.querySelector('.lcard');lv.addEventListener('mousemove',e=>{const r=lv.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;cards.forEach((c,i)=>{const d=(i+1)*6;c.style.transform='translate('+x*d+'px,'+y*d+'px)';});if(card)card.style.transform='translate('+x*2+'px,'+y*2+'px)';});lv.addEventListener('mouseleave',()=>{cards.forEach(c=>c.style.transform='');if(card)card.style.transform='';});}[$('logEmail'),$('logPass')].forEach(el=>{if(el)el.addEventListener('keydown',e=>{if(e.key==='Enter')doLogin();});});}
function doLogin(asGuest){const em=($('logEmail')?.value||'demo@valora.com').trim();if(asGuest){S.user={name:'Invitado',init:'IN'};}else{const name=em.split('@')[0].replace(/[._]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());S.user={name,init:name.split(' ').map(w=>w[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'US'};}const nu=$('navUser');if(nu)nu.textContent=S.user.init;$('loginView').style.display='none';$('appShell').style.display='flex';initLogos();applyTheme(S.theme);updateGreeting();logActivity('login','Sesion iniciada','<b>'+S.user.name+'</b> ingreso a VALORA','b');renderDashboard();renderHistory();}
function doLogout(){if(!confirm('Cerrar sesion de VALORA?'))return;$('loginView').style.display='flex';$('appShell').style.display='none';}
function updateGreeting(){const h=new Date().getHours(),g=h<12?'Buenos dias':h<19?'Buenas tardes':'Buenas noches';$('greetTxt').textContent=g+', '+S.user.name.split(' ')[0];$('dateTxt').textContent=new Date().toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());}
function switchView(v){S.view=v;['dash','map','hist'].forEach(n=>{const el=$(n+'View');if(el)el.style.display=n===v?'flex':'none';});document.querySelectorAll('.nav-i').forEach(b=>b.classList.toggle('on',b.dataset.view===v));const cc=$('crumbCur');if(cc)cc.textContent={dash:'Dashboard',map:'Visualizador',hist:'Actividad'}[v]||v;if(v==='dash')renderDashboard();if(v==='hist')renderHistory();if(v==='map'&&S.svgEl)setTimeout(()=>applyT(),50);}
function logActivity(type,title,msg,ic){S.activity.unshift({type,title,msg,t:Date.now(),ic:ic||'b',user:S.user.name});if(S.activity.length>100)S.activity.pop();if(S.view==='dash')renderFeed();if(S.view==='hist')renderHistory();}
function timeAgo(ts){const d=Date.now()-ts,m=Math.floor(d/60000),h=Math.floor(m/60),da=Math.floor(h/24);if(da>0)return 'hace '+da+'d';if(h>0)return 'hace '+h+'h';if(m>0)return 'hace '+m+'m';return 'ahora';}
const ICO={upload:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17,8 12,3 7,8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>',edit:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4z"/></svg>',filter:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><polygon points="22,3 2,3 10,12.46 10,19 14,21 14,12.46"/></svg>',login:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10,17 15,12 10,7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>',check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><polyline points="20,6 9,17 4,12"/></svg>',view:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>'};
function renderDashboard(){renderKpis();renderDistribution();renderFeed();}
function renderKpis(){const c=$('kpiGrid');if(!c)return;c.innerHTML='';if(!S.rows.length){c.innerHTML='<div class="kpi-card"><div class="kpi-bar b"></div><div class="kpi-head"><div class="kpi-lbl">Total lotes</div><div class="kpi-icon b">'+ICO.view+'</div></div><div class="kpi-num">-</div><div class="kpi-foot"><span>Sin datos cargados</span></div></div><div class="kpi-card"><div class="kpi-bar g"></div><div class="kpi-head"><div class="kpi-lbl">Disponibles</div><div class="kpi-icon g">'+ICO.check+'</div></div><div class="kpi-num">-</div><div class="kpi-foot"><span>Carga un archivo Excel</span></div></div><div class="kpi-card"><div class="kpi-bar r"></div><div class="kpi-head"><div class="kpi-lbl">Vendidos</div><div class="kpi-icon r">'+ICO.check+'</div></div><div class="kpi-num">-</div><div class="kpi-foot"><span>-</span></div></div><div class="kpi-card"><div class="kpi-bar a"></div><div class="kpi-head"><div class="kpi-lbl">Reservados</div><div class="kpi-icon a">'+ICO.check+'</div></div><div class="kpi-num">-</div><div class="kpi-foot"><span>-</span></div></div>';return;}const ce=C.est(),tot=S.rows.length,counts={};S.rows.forEach(r=>{const v=String(r[ce]||'').trim();if(v)counts[v]=(counts[v]||0)+1;});const ord=['Disponible','Libre','Vendido','Reservado','Separado'],keys=[...new Set([...ord.filter(k=>counts[k]),...Object.keys(counts)])],clsM={Disponible:'g',Libre:'g',Vendido:'r',Reservado:'a',Separado:'a'};const cards=['<div class="kpi-card"><div class="kpi-bar b"></div><div class="kpi-head"><div class="kpi-lbl">Total lotes</div><div class="kpi-icon b">'+ICO.view+'</div></div><div class="kpi-num">'+tot+'</div><div class="kpi-foot"><span>en el proyecto</span><span class="kpi-delta up">activo</span></div></div>'];keys.slice(0,3).forEach(k=>{const n=counts[k]||0,pc=Math.round(n/tot*100),cls=clsM[k]||'v';cards.push('<div class="kpi-card"><div class="kpi-bar '+cls+'"></div><div class="kpi-head"><div class="kpi-lbl">'+k+'</div><div class="kpi-icon '+cls+'">'+ICO.check+'</div></div><div class="kpi-num">'+n+'</div><div class="kpi-foot"><span>'+pc+'% del total</span><span class="kpi-delta up">'+pc+'%</span></div></div>');});c.innerHTML=cards.join('');}
function renderDistribution(){const c=$('distBody');if(!c)return;if(!S.rows.length){c.innerHTML='<div class="feed-empty">Carga un Excel para ver la distribucion</div>';$('distSub').textContent='Sin datos';return;}const ce=C.est(),tot=S.rows.length,counts={};S.rows.forEach(r=>{const v=String(r[ce]||'').trim();if(v)counts[v]=(counts[v]||0)+1;});const entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);$('distSub').textContent=tot+' lotes '+entries.length+' estados';let acc=0;const stops=[];entries.forEach(([k,v])=>{const pc=v/tot*100,col=S.sc[k]||'#94a3b8';stops.push(col+' '+acc+'% '+(acc+pc)+'%');acc+=pc;});const leg=entries.map(([k,v])=>{const pc=Math.round(v/tot*100),col=S.sc[k]||'#94a3b8';return '<div class="dl-item"><div class="dl-dot" style="background:'+col+'"></div><div class="dl-nm">'+k+'</div><div class="dl-ct">'+v+'</div><div class="dl-pc">'+pc+'%</div></div>';}).join('');c.innerHTML='<div class="donut-wrap"><div class="donut" style="background:conic-gradient('+stops.join(',')+'5);-webkit-mask:radial-gradient(circle,transparent 52%,#000 53%);mask:radial-gradient(circle,transparent 52%,#000 53%)"></div><div class="donut-center"><div class="donut-cn">'+tot+'</div><div class="donut-cl">Total</div></div><div class="donut-leg">'+leg+'</div></div>';}
function renderFeed(){const c=$('feedBody');if(!c)return;if(!S.activity.length){c.innerHTML='<div class="feed-empty">Sin actividad reciente</div>';return;}c.innerHTML=S.activity.slice(0,6).map(a=>'<div class="feed-i"><div class="feed-ic '+a.ic+'">'+(ICO[a.type]||ICO.edit)+'</div><div><div class="feed-msg">'+a.msg+'</div><div class="feed-time">'+timeAgo(a.t)+' '+a.user+'</div></div></div>').join('');}
function renderHistory(){const c=$('histBody');if(!c)return;if(!S.activity.length){c.innerHTML='<div class="timeline"><div class="hist-empty">Sin actividad registrada todavia</div></div>';return;}const groups={},bgM={b:'var(--ac-bg)',g:'var(--grn-bg)',r:'var(--red-bg)',a:'var(--amb-bg)',v:'var(--vio-bg)'},txM={b:'var(--ac)',g:'var(--grn-tx)',r:'var(--red-tx)',a:'var(--amb-tx)',v:'var(--vio-tx)'};S.activity.forEach(a=>{const d=new Date(a.t).toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'});(groups[d]=groups[d]||[]).push(a);});let html='<div class="timeline">';Object.entries(groups).forEach(([d,items])=>{html+='<div class="tl-day">'+d+'</div>';items.forEach(a=>{const time=new Date(a.t).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'});html+='<div class="tl-i"><div class="tl-ic" style="background:'+(bgM[a.ic]||bgM.b)+';color:'+(txM[a.ic]||txM.b)+'">'+(ICO[a.type]||ICO.edit)+'</div><div><div class="tl-msg">'+a.msg+'</div><div class="tl-meta">'+time+' <span class="tl-user">'+a.user+'</span></div></div></div>';});});c.innerHTML=html+'</div>';}
function h2h(hex){const r=parseInt(hex.slice(1,3),16)/255,g=parseInt(hex.slice(3,5),16)/255,b=parseInt(hex.slice(5,7),16)/255,mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0,s=0,l=(mx+mn)/2;if(d){s=l>.5?d/(2-mx-mn):d/(mx+mn);h=(mx===r?(g-b)/d+(g<b?6:0):mx===g?(b-r)/d+2:(r-g)/d+4)/6;}return{h:h*360,s:s*100,l:l*100};}
function h2x(h,s,l){h/=360;s/=100;l/=100;const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q,f=t=>{t=((t%1)+1)%1;return t<1/6?p+(q-p)*6*t:t<.5?q:t<2/3?p+(q-p)*(2/3-t)*6:p;};return'#'+[h+1/3,h,h-1/3].map(c=>Math.round(f(c)*255).toString(16).padStart(2,'0')).join('');}
function subClr(base,i,n){const{h,s,l}=h2h(base);return h2x(h,clamp(s+5,30,90),clamp(l-15+(n>1?i*(30/(n-1)):0),25,70));}
function getGroups(){const g=[],ce=C.est(),cs=C.sub(),cp=C.pay(),cps=C.payS();if(ce)g.push({id:'estado',label:'Estados',icon:'o',col:ce,subCol:cs||null});if(cp&&cp!==ce)g.push({id:'pago',label:'Financiamiento',icon:'*',col:cp,subCol:cps||null});return g;}
function getClr(col,val){if(col===C.est())return S.sc[val]||'#94a3b8';if(!S.gc[col])S.gc[col]={};if(!S.gc[col][val])S.gc[col][val]=DEF[nrm(val)]||nextClr();return S.gc[col][val];}
function getSubClr(col,val,sub){return S.gsc[col]?.[val]?.[sub]||getClr(col,val);}
function buildColors(){const ce=C.est();[...new Set(S.rows.map(r=>String(r[ce]||'').trim()).filter(Boolean))].forEach(v=>{if(!S.sc[v])S.sc[v]=DEF[nrm(v)]||nextClr();});getGroups().filter(g=>g.col!==ce).forEach(g=>{[...new Set(S.rows.map(r=>String(r[g.col]||'').trim()).filter(Boolean))].forEach(v=>getClr(g.col,v));});}
function buildSubColors(){S.gsc={};getGroups().forEach(g=>{if(!g.subCol)return;if(!S.gsc[g.col])S.gsc[g.col]={};[...new Set(S.rows.map(r=>String(r[g.col]||'').trim()).filter(Boolean))].forEach(val=>{const base=getClr(g.col,val),subs=[...new Set(S.rows.filter(r=>String(r[g.col]||'').trim()===val).map(r=>String(r[g.subCol]||'').trim()).filter(Boolean))];S.gsc[g.col][val]={};subs.forEach((s,i)=>S.gsc[g.col][val][s]=subClr(base,i,subs.length));});});}
function applyT(anim){const cv=$('canvas'),mc=$('mapEl');if(!cv||!mc)return;cv.style.transition=anim?'transform .22s cubic-bezier(.4,0,.2,1)':'none';cv.style.transform='translate('+S.cam.x+'px,'+S.cam.y+'px) scale('+S.cam.z+')';mc.style.transform='rotate('+S.cam.r+'deg)';const z=$('zlbl');if(z)z.textContent=Math.round(S.cam.z*100);}
function fitView(anim){if(!S.svgEl)return;const vp=$('vp'),W=S.dims.w,H=S.dims.h,vpW=vp.clientWidth,vpH=vp.clientHeight;if(vpW<10||vpH<10){setTimeout(()=>fitView(anim),60);return;}const r=((S.cam.r%360)+360)%360,eW=(r===90||r===270)?H:W,eH=(r===90||r===270)?W:H;S.cam.z=clamp(Math.min(vpW/eW,vpH/eH)*.9,MIN_Z,MAX_Z);S.cam.x=vpW/2-(W/2)*S.cam.z;S.cam.y=vpH/2-(H/2)*S.cam.z;applyT(anim);}
function dz(f){const vp=$('vp'),r=vp.getBoundingClientRect();zAt(r.left+r.width/2,r.top+r.height/2,f);}
function zAt(cx,cy,f){const nz=clamp(S.cam.z*f,MIN_Z,MAX_Z),vp=$('vp'),r=vp.getBoundingClientRect(),x=cx-r.left,y=cy-r.top,rt=nz/S.cam.z;S.cam.x=x-(x-S.cam.x)*rt;S.cam.y=y-(y-S.cam.y)*rt;S.cam.z=nz;applyT();}
function doRot(d){S.cam.r=((S.cam.r+d)%360+360)%360;fitView(true);}
function refit(){if(!S.svgEl)return;S.cam.r=0;fitView(true);}
function setupViewportEvents(){const vp=$('vp');vp.addEventListener('mousedown',e=>{if(e.button!==0)return;e.preventDefault();S.drag={on:true,sx:e.clientX,sy:e.clientY,px:S.cam.x,py:S.cam.y};vp.classList.add('drg');});window.addEventListener('mousemove',e=>{if(!S.drag.on)return;S.cam.x=S.drag.px+(e.clientX-S.drag.sx);S.cam.y=S.drag.py+(e.clientY-S.drag.sy);applyT();});window.addEventListener('mouseup',()=>{S.drag.on=false;vp.classList.remove('drg');});vp.addEventListener('wheel',e=>{e.preventDefault();zAt(e.clientX,e.clientY,e.deltaY>0?1/ZF:ZF);},{passive:false});vp.addEventListener('touchstart',e=>{if(e.touches.length===1){S.drag={on:true,sx:e.touches[0].clientX,sy:e.touches[0].clientY,px:S.cam.x,py:S.cam.y};}else if(e.touches.length===2){S.drag.on=false;S.tdist=Math.hypot(e.touches[1].clientX-e.touches[0].clientX,e.touches[1].clientY-e.touches[0].clientY);}e.preventDefault();},{passive:false});vp.addEventListener('touchmove',e=>{e.preventDefault();if(e.touches.length===1&&S.drag.on){S.cam.x=S.drag.px+(e.touches[0].clientX-S.drag.sx);S.cam.y=S.drag.py+(e.touches[0].clientY-S.drag.sy);applyT();}else if(e.touches.length===2){const nd=Math.hypot(e.touches[1].clientX-e.touches[0].clientX,e.touches[1].clientY-e.touches[0].clientY);zAt((e.touches[0].clientX+e.touches[1].clientX)/2,(e.touches[0].clientY+e.touches[1].clientY)/2,nd/S.tdist);S.tdist=nd;}},{passive:false});vp.addEventListener('touchend',()=>{S.drag.on=false;});}
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(e.key==='Escape'){closeDP();clearFilter();}if(e.key==='f'||e.key==='F')fitView(true);});
document.getElementById('fXls').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];S.rows=XLSX.utils.sheet_to_json(ws,{defval:''}).map(row=>{const o={};Object.keys(row).forEach(k=>{o[String(k).trim()]=String(row[k]??'').trim();});return o;});if(!S.rows.length){toast('El Excel no contiene datos','err');return;}setupCols(f.name);logActivity('upload','Excel cargado','<b>'+f.name+'</b> '+S.rows.length+' lotes detectados','g');}catch(ex){toast('Error al leer Excel: '+ex.message,'err');}};rd.onerror=()=>toast('No se pudo leer el archivo','err');rd.readAsArrayBuffer(f);e.target.value='';});
document.getElementById('fSvg').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=ev=>loadSVG(ev.target.result,f.name);rd.onerror=()=>toast('No se pudo leer el SVG','err');rd.readAsText(f,'UTF-8');e.target.value='';});
function rebuildRowById(){S.rowById={};S.rows.forEach(r=>{const id=String(r[C.id()]||'').trim();if(id)S.rowById[id]=r;});}
function setupCols(fname){const cols=Object.keys(S.rows[0]);['cId','cEst','cPr'].forEach(id=>{const el=$(id);if(el)el.innerHTML=cols.map(c=>'<option value="'+c+'">'+c+'</option>').join('');});['cSub','cPay','cPayS'].forEach(id=>{const el=$(id);if(el)el.innerHTML='<option value="">Ninguno</option>'+cols.map(c=>'<option value="'+c+'">'+c+'</option>').join('');});const lo=cols.map(c=>c.toLowerCase()),g=(...kw)=>{for(const k of kw){const i=lo.findIndex(l=>l.includes(k));if(i>=0)return cols[i];}return'';};const ci=$('cId'),ce=$('cEst'),cp=$('cPr');if(ci)ci.value=g('id','lote','cod','num','manz','lot','nro')||cols[0];if(ce)ce.value=g('estado','status','condicion','disponib')||cols[Math.min(1,cols.length-1)];if(cp)cp.value=g('precio','price','valor','monto')||cols[0];const sg=g('subtipo','ubicacion','tipo','categoria'),cs=$('cSub');if(sg&&cs)cs.value=sg;const pg=g('financ','pago','modalidad'),cpay=$('cPay');if(pg&&cpay)cpay.value=pg;const pgs=g('cuotas','plazo','meses'),cpays=$('cPayS');if(pgs&&cpays&&pgs!==pg)cpays.value=pgs;const cs2=$('colSec');if(cs2)cs2.style.display='';[$('upXls'),$('scXls')].forEach(el=>{if(el)el.classList.add('ok');});const st=$('scXlsSt');if(st)st.textContent=fname;const eb=$('expBtn');if(eb)eb.style.display='inline-flex';rebuildAll();}
function rebuildAll(){rebuildRowById();buildColors();buildSubColors();renderLegend();renderMiniKpis();renderColors();populateFilters();scheduleApply();renderDashboard();}
function scheduleApply(){if(S.raf)cancelAnimationFrame(S.raf);S.raf=requestAnimationFrame(()=>{S.raf=null;applyColors();});}
function applyColors(){if(!S.svgEl||!S.rows.length)return;const ci=C.id(),ce=C.est();if(!ci||!ce)return;let matched=0;S.rows.forEach(row=>{const lid=String(row[ci]||'').trim(),est=String(row[ce]||'').trim(),el=findEl(lid);if(!el)return;matched++;setFill(el,S.sc[est]||'#94a3b8');let vis=true;if(S.filter){const rv=String(row[S.filter.col]||'').trim();vis=rv.toLowerCase()===S.filter.value.toLowerCase();if(vis&&S.filter.subValue&&S.filter.subCol)vis=String(row[S.filter.subCol]||'').trim().toLowerCase()===S.filter.subValue.toLowerCase();}el.style.opacity=vis?'1':'0.07';el.style.cursor='pointer';el.dataset.lid=lid;el.dataset.est=est;});const mi=$('matchMsg');if(!mi)return;if(matched===0)mi.className='mi err',mi.innerHTML='Sin coincidencias con columna "<b>'+C.id()+'</b>". Muestra: '+Object.keys(S.lotMap).slice(0,4).join(', ');else if(matched<S.rows.length)mi.className='mi warn',mi.textContent=matched+' de '+S.rows.length+' lotes encontrados.';else mi.className='mi ok',mi.textContent='v '+matched+' lotes conectados correctamente.';}
function loadSVG(txt,fname){if(S.view!=='map')switchView('map');setTimeout(()=>{showLoader('Cargando plano...');const mc=$('mapEl');let s=txt.trim().replace(/^<\?xml[^>]*\?>\s*/i,'').replace(/<!DOCTYPE[^>]*>\s*/i,'');const si=s.indexOf('<svg');if(si<0){hideLoader();toast('Archivo SVG no valido','err');return;}mc.innerHTML=s.slice(si);S.svgEl=mc.querySelector('svg');if(!S.svgEl){mc.innerHTML='';hideLoader();toast('Error al procesar el plano','err');return;}S.svgEl.removeAttribute('width');S.svgEl.removeAttribute('height');S.svgEl.style.cssText='display:block;background:none;overflow:visible';requestAnimationFrame(()=>requestAnimationFrame(()=>finalizeSVG(fname)));},50);}
function finalizeSVG(fname){if(!S.svgEl)return;const b=realBounds();let vx,vy,vw,vh;if(b&&b.w>0){const pad=Math.max(b.w,b.h)*.05;vx=b.x-pad;vy=b.y-pad;vw=b.w+pad*2;vh=b.h+pad*2;}else{const vbP=(S.svgEl.getAttribute('viewBox')||'0 0 800 600').split(/[\s,]+/).map(Number).filter(n=>!isNaN(n));[vx,vy,vw,vh]=vbP.length>=4?vbP:[0,0,800,600];}S.svgEl.setAttribute('viewBox',vx+' '+vy+' '+vw+' '+vh);const sc=Math.min(1,2000/Math.max(vw,vh)),cw=Math.max(200,Math.round(vw*sc)),ch=Math.max(200,Math.round(vh*sc));S.svgEl.style.width=cw+'px';S.svgEl.style.height=ch+'px';S.dims={w:cw,h:ch};try{S.svgEl.querySelectorAll('rect').forEach(el=>{const f=(el.getAttribute('fill')||el.style.fill||'').toLowerCase().replace(/\s/g,'');if(!['white','#fff','#ffffff'].includes(f))return;if(parseFloat(el.getAttribute('width'))>=vw*.8&&parseFloat(el.getAttribute('height'))>=vh*.8)el.style.display='none';});}catch(e){}S.lotMap={};S.svgEl.querySelectorAll('[id]').forEach(el=>{if(el.closest('defs')||el.closest('symbol'))return;const id=(el.id||'').trim();if(id)S.lotMap[nrm(id)]=el;});hideLoader();const em=$('empty');if(em)em.style.display='none';const ct=$('ctrl');if(ct)ct.style.display='flex';[$('upSvg'),$('scSvg')].forEach(el=>{if(el)el.classList.add('ok');});const st=$('scSvgSt');if(st)st.textContent=fname;S.cam.r=0;fitView(false);setupSVGEvents();if(S.rows.length)scheduleApply();const count=Object.keys(S.lotMap).length;logActivity('upload','Plano cargado','<b>'+fname+'</b> cargado '+count+' elementos detectados','b');toast('Plano listo '+count+' elementos','ok');}
function realBounds(){if(!S.svgEl)return null;try{const b=S.svgEl.getBBox();if(b.width>0)return{x:b.x,y:b.y,w:b.width,h:b.height};}catch(e){}let mx=Infinity,my=Infinity,xX=-Infinity,xY=-Infinity;S.svgEl.querySelectorAll('path,rect,circle,ellipse,polygon,polyline').forEach(el=>{try{if(el.closest('defs'))return;const b=el.getBBox();if(!b.width&&!b.height)return;mx=Math.min(mx,b.x);my=Math.min(my,b.y);xX=Math.max(xX,b.x+b.width);xY=Math.max(xY,b.y+b.height);}catch(e){}});return isFinite(mx)?{x:mx,y:my,w:xX-mx,h:xY-my}:null;}
function findEl(rawId){const nk=nrm(rawId);if(S.lotMap[nk])return S.lotMap[nk];const px=['lote','lot','l','id','mz','manzana','lt','parcela'];for(const p of px){if(S.lotMap[p+nk])return S.lotMap[p+nk];for(const k of Object.keys(S.lotMap))if(k.replace(new RegExp('^('+px.join('|')+')',''),'')===nk)return S.lotMap[k];}return null;}
function setFill(el,color){const ap=e=>{const t=(e.tagName||'').toLowerCase();if(['text','tspan','defs','style'].includes(t))return;if(e.getAttribute('fill')==='none')return;e.setAttribute('fill',color);e.style.fill=color;};ap(el);el.querySelectorAll('path,rect,polygon,circle,ellipse').forEach(ap);el.style.transition='opacity .12s,fill .12s';}
function setupSVGEvents(){if(!S.svgEl)return;S.svgEl.addEventListener('mousemove',e=>{if(S.drag.on){$('tt').style.display='none';return;}const t=e.target.closest('[data-lid]');if(!t){$('tt').style.display='none';return;}const row=S.rowById[t.dataset.lid];if(!row){$('tt').style.display='none';return;}const tt=$('tt');tt.style.display='block';const x=e.clientX+14,y=e.clientY+12;tt.style.left=(x+240>innerWidth?x-258:x)+'px';tt.style.top=(y+180>innerHeight?y-180:y)+'px';$('ttDot').style.background=S.sc[t.dataset.est]||'#94a3b8';$('ttId').textContent=t.dataset.lid;$('ttEst').textContent=t.dataset.est;const b=$('ttB');b.innerHTML='';const addR=(k,v)=>{const d=mk('div','tt-r');d.innerHTML='<span class="tt-k">'+k+'</span><span class="tt-v">'+v+'</span>';b.appendChild(d);};const cp=C.pr(),cs=C.sub(),cpay=C.pay(),cpayS=C.payS();if(cp&&row[cp])addR('Precio',fmtP(row[cp]));if(cs&&row[cs])addR(fmtL(cs),row[cs]);if(cpay&&row[cpay])addR(fmtL(cpay),row[cpay]);if(cpayS&&row[cpayS])addR(fmtL(cpayS),row[cpayS]);});S.svgEl.addEventListener('mouseleave',()=>{$('tt').style.display='none';});S.svgEl.addEventListener('click',e=>{if(S.drag.on)return;const t=e.target.closest('[data-lid]');if(t)openDP(t.dataset.lid,t);});}
function clickItem(col,val){S.filter=S.filter?.col===col&&S.filter?.value===val&&!S.filter?.subValue?null:{col,value:val,subCol:null,subValue:null};if(S.filter)S.exp.add(col+':'+val);renderLegend();renderMiniKpis();updateFB();scheduleApply();if(S.filter)logActivity('filter','Filtro','Filtro aplicado: <b>'+val+'</b>','v');}
function clickSub(col,val,subCol,subVal){S.filter=S.filter?.col===col&&S.filter?.value===val&&S.filter?.subValue===subVal?{col,value:val,subCol:null,subValue:null}:{col,value:val,subCol,subValue:subVal};renderLegend();renderMiniKpis();updateFB();scheduleApply();}
function toggleExp(col,val){const k=col+':'+val;S.exp.has(k)?S.exp.delete(k):S.exp.add(k);renderLegend();}
function clearFilter(){S.filter=null;renderLegend();renderMiniKpis();updateFB();scheduleApply();}
function updateFB(){const b=$('fbadge'),clr=$('clrBtn');if(S.filter){if(b){b.style.display='flex';const fl=$('fbLbl');if(fl){let l=S.filter.value;if(S.filter.subValue)l+=' > '+S.filter.subValue;fl.textContent=l;}}if(clr)clr.classList.add('show');}else{if(b)b.style.display='none';if(clr)clr.classList.remove('show');}}
function renderLegend(){if(!S.rows.length)return;const groups=getGroups();if(!groups.length)return;if(!S.tab||!groups.find(g=>g.id===S.tab))S.tab=groups[0].id;const el=$('tabs');if(el){el.style.display=groups.length>1?'flex':'none';if(groups.length>1){el.innerHTML='';groups.forEach(g=>{const btn=mk('button','tab'+(g.id===S.tab?' on':''));btn.innerHTML='<span>'+g.icon+'</span><span>'+g.label+'</span>';btn.onclick=()=>{S.tab=g.id;const lb=$('lgBody');if(lb){lb.classList.remove('lg-anim');void lb.offsetWidth;lb.classList.add('lg-anim');}renderLegend();};el.appendChild(btn);});}}const ag=groups.find(g=>g.id===S.tab)||groups[0];if(!ag)return;const lb=$('lgBody');if(!lb)return;lb.innerHTML='';const tot=S.rows.length,vals=[...new Set(S.rows.map(r=>String(r[ag.col]||'').trim()).filter(Boolean))];vals.forEach(val=>{const cnt=S.rows.filter(r=>String(r[ag.col]||'').trim()===val).length,pct=Math.round(cnt/tot*100),color=getClr(ag.col,val),isAct=S.filter?.col===ag.col&&S.filter?.value===val&&!S.filter?.subValue,isExp=S.exp.has(ag.col+':'+val);const subs=ag.subCol?[...new Set(S.rows.filter(r=>String(r[ag.col]||'').trim()===val).map(r=>String(r[ag.subCol]||'').trim()).filter(Boolean))]:[];const wrap=mk('div','lg-item'),row=mk('div','lg-row'+(isAct?' on':''));row.onclick=()=>clickItem(ag.col,val);const sq=mk('div','lg-sq');sq.style.background=color;row.append(sq,mk('span','lg-nm',val),mk('span','lg-ct',cnt),mk('span','lg-pc',pct+'%'));if(subs.length){const btn=mk('button','lg-ex',isExp?'v':'>');btn.onclick=e=>{e.stopPropagation();toggleExp(ag.col,val);};row.appendChild(btn);}const bar=mk('div','lg-bar'),fill=mk('div','lg-bfill');fill.style.cssText='width:'+pct+'%;background:'+color;bar.appendChild(fill);wrap.append(row,bar);if(isExp&&subs.length){const sl=mk('div','lg-subs');sl.style.maxHeight=subs.length*30+'px';subs.forEach(sub=>{const sc_=S.rows.filter(r=>String(r[ag.col]||'').trim()===val&&String(r[ag.subCol]||'').trim()===sub).length,scol=getSubClr(ag.col,val,sub),isSubAct=S.filter?.col===ag.col&&S.filter?.value===val&&S.filter?.subValue===sub,se=mk('div','lg-sub'+(isSubAct?' on':''));const sd=mk('div','lg-sdot');sd.style.background=scol;se.append(sd,mk('span','lg-snm',sub),mk('span','lg-sct',sc_));se.onclick=()=>clickSub(ag.col,val,ag.subCol,sub);sl.appendChild(se);});wrap.appendChild(sl);}lb.appendChild(wrap);});updateFB();}
function renderMiniKpis(){const c=$('miniKpis');if(!c||!S.rows.length){if(c)c.innerHTML='';return;}c.innerHTML='';const ce=C.est(),tot=S.rows.length,vals=[...new Set(S.rows.map(r=>String(r[ce]||'').trim()).filter(Boolean))];vals.slice(0,4).forEach(v=>{const cnt=S.rows.filter(r=>String(r[ce]||'').trim()===v).length,pct=Math.round(cnt/tot*100),color=S.sc[v]||'#94a3b8',isAct=S.filter?.col===ce&&S.filter?.value===v,k=mk('div','mk'+(isAct?' on':''));k.innerHTML='<div class="mk-bar" style="background:'+color+'"></div><div class="mk-top"><div class="mk-dot" style="background:'+color+'"></div><div class="mk-lbl">'+v+'</div></div><div><span class="mk-num">'+cnt+'</span><span class="mk-pc"> '+pct+'%</span></div>';k.onclick=()=>clickItem(ce,v);c.appendChild(k);});}
function renderColors(){const cs=$('colorSec');if(cs)cs.style.display='';const c=$('colorRows');if(!c)return;c.innerHTML='';getGroups().forEach((group,gi)=>{if(getGroups().length>1){const lbl=mk('div','sec-t');lbl.style.marginTop=gi>0?'12px':'0';lbl.textContent=group.label;c.appendChild(lbl);}[...new Set(S.rows.map(r=>String(r[group.col]||'').trim()).filter(Boolean))].forEach(val=>{const cnt=S.rows.filter(r=>String(r[group.col]||'').trim()===val).length,color=getClr(group.col,val),d=mk('div','cr');d.innerHTML='<div class="cr-d" style="background:'+color+'"></div><span class="cr-n">'+val+'</span><span class="cr-c">'+cnt+'</span><input type="color" value="'+color+'" data-col="'+group.col+'" data-val="'+encodeURIComponent(val)+'" data-isest="'+(group.col===C.est()?1:0)+'" onchange="updColor(this)">';c.appendChild(d);});}); }
function updColor(inp){const col=inp.dataset.col,val=decodeURIComponent(inp.dataset.val);if(inp.dataset.isest==='1')S.sc[val]=inp.value;else{if(!S.gc[col])S.gc[col]={};S.gc[col][val]=inp.value;}inp.closest('.cr').querySelector('.cr-d').style.background=inp.value;buildSubColors();renderLegend();renderMiniKpis();scheduleApply();renderDashboard();}
function doSearch(){const q=($('srchIn')?.value||'').trim();if(!q)return;if(S.view!=='map'){switchView('map');setTimeout(doSearch,200);return;}const el=findEl(nrm(q));if(!el){toast('Lote "'+q+'" no encontrado','err');return;}focusEl(el);const row=S.rows.find(r=>nrm(String(r[C.id()]||'').trim())===nrm(q));if(row)openDP(String(row[C.id()]||'').trim(),el);}
function focusEl(el){if(!el||!S.svgEl)return;try{const bb=el.getBBox();if(!bb||(!bb.width&&!bb.height))return;const cx=bb.x+bb.width/2,cy=bb.y+bb.height/2,vbP=(S.svgEl.getAttribute('viewBox')||'0 0 '+S.dims.w+' '+S.dims.h).split(/[\s,]+/).map(Number),vbX=vbP[0]||0,vbY=vbP[1]||0,vbW=vbP[2]||S.dims.w,vbH=vbP[3]||S.dims.h,pxX=(cx-vbX)/vbW*S.dims.w,pxY=(cy-vbY)/vbH*S.dims.h,rad=S.cam.r*Math.PI/180,dx=pxX-S.dims.w/2,dy=pxY-S.dims.h/2,canX=S.dims.w/2+dx*Math.cos(rad)-dy*Math.sin(rad),canY=S.dims.h/2+dx*Math.sin(rad)+dy*Math.cos(rad),vp=$('vp'),sz=Math.max(bb.width/vbW*S.dims.w,bb.height/vbH*S.dims.h,20);S.cam.z=clamp(Math.min(vp.offsetWidth,vp.offsetHeight)/sz/4,1,MAX_Z);S.cam.x=vp.offsetWidth/2-canX*S.cam.z;S.cam.y=vp.offsetHeight/2-canY*S.cam.z;applyT(true);}catch(e){}}
function openDP(lid,el){const row=S.rowById[lid]||S.rows.find(r=>String(r[C.id()]||'').trim()===lid);if(!row)return;if(S.hlEl&&S.hlEl!==el)S.hlEl.style.stroke='';el.style.stroke='#60a5fa';el.style.strokeWidth=String(2/S.cam.z);S.hlEl=el;const est=String(row[C.est()]||'').trim(),color=S.sc[est]||'#94a3b8';$('dpId').textContent=lid;$('dpSt').textContent=est;$('dpStDot').style.background=color;const sts=[...new Set(S.rows.map(r=>String(r[C.est()]||'').trim()).filter(Boolean))];const sel=$('dpSel');sel.innerHTML=sts.map(s=>'<option value="'+s+'"'+(s===est?' selected':'')+'>'+s+'</option>').join('');sel.dataset.lid=lid;const body=$('dpBody');body.innerHTML='';const cp=C.pr();Object.keys(row).forEach(k=>{if(!row[k]||k===C.id()||k===C.est())return;const isP=k===cp,v=isP?fmtP(row[k]):row[k],d=mk('div','dpf');d.innerHTML='<span class="dpf-l">'+k+'</span><span class="'+(isP?'dpf-vp':'dpf-v')+'">'+v+'</span>';body.appendChild(d);});$('dp').classList.add('open');S.selLot=lid;}
function closeDP(){$('dp').classList.remove('open');if(S.hlEl){S.hlEl.style.stroke='';S.hlEl=null;}S.selLot=null;}
function changeSt(sel){const lid=sel.dataset.lid;if(!lid)return;const row=S.rowById[lid];if(!row)return;const ce=C.est(),old=row[ce],nv=sel.value;row[ce]=nv;if(!S.sc[nv])S.sc[nv]=nextClr();const el=findEl(lid);if(el){setFill(el,S.sc[nv]);el.dataset.est=nv;}$('dpSt').textContent=nv;$('dpStDot').style.background=S.sc[nv];buildColors();buildSubColors();renderColors();renderLegend();renderMiniKpis();renderDashboard();logActivity('edit','Estado modificado','Lote <b>'+lid+'</b>: <b>'+old+'</b> to <b>'+nv+'</b>','a');}
function openSet(){const el=$('setMask');if(el)el.classList.add('show');}function closeSet(){const el=$('setMask');if(el)el.classList.remove('show');}
function openTbl(){if(!S.rows.length){toast('Carga un Excel primero','err');return;}const el=$('tblMask');if(el)el.classList.add('show');renderTbl();}function closeTbl(){const el=$('tblMask');if(el)el.classList.remove('show');}
function populateFilters(){const tf=$('tsfil');if(tf)tf.innerHTML='<option value="">Todos los estados</option>'+[...new Set(S.rows.map(r=>String(r[C.est()]||'').trim()).filter(Boolean))].map(s=>'<option value="'+s+'">'+s+'</option>').join('');const cp=C.pay(),el=$('tsfilP');if(cp&&el){el.innerHTML='<option value="">Todo financiamiento</option>'+[...new Set(S.rows.map(r=>String(r[cp]||'').trim()).filter(Boolean))].map(s=>'<option value="'+s+'">'+s+'</option>').join('');el.style.display='';}else if(el)el.style.display='none';}
function renderTbl(){if(!S.rows.length)return;const cols=Object.keys(S.rows[0]);const srch=($('tsrch')?.value||'').toLowerCase(),sf=$('tsfil')?.value||'',sfp=$('tsfilP')?.value||'';const filt=S.rows.filter(r=>{const ms=!srch||Object.values(r).some(v=>String(v).toLowerCase().includes(srch));return ms&&(!sf||String(r[C.est()]||'').trim()===sf)&&(!sfp||String(r[C.pay()]||'').trim()===sfp);});const tc=$('tblCnt');if(tc)tc.textContent=filt.length+' de '+S.rows.length+' lotes';const th=$('thead');if(th)th.innerHTML='<tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'</tr>';const sts=[...new Set(S.rows.map(r=>String(r[C.est()]||'').trim()).filter(Boolean))];const tb=$('tbody');if(!tb)return;tb.innerHTML=filt.slice(0,200).map(r=>{const gi=S.rows.indexOf(r),lid=String(r[C.id()]||'').trim(),est=String(r[C.est()]||'').trim(),col=S.sc[est]||'#94a3b8';return'<tr class="'+(lid===S.selLot?'sel':'')+'" onclick="fromTbl(event,\''+lid+'\')">'+ cols.map(c=>{if(c===C.est())return'<td><select class="esel" style="background:'+col+'" data-i="'+gi+'" data-c="'+c+'" onchange="onCell(this)" onclick="event.stopPropagation()">'+sts.map(s=>'<option value="'+s+'"'+(s===est?' selected':'')+'>'+s+'</option>').join('')+'</select></td>';return'<td><input class="ecell" value="'+String(r[c]).replace(/"/g,'&quot;').replace(/</g,'&lt;')+'" data-i="'+gi+'" data-c="'+c+'" onchange="onCell(this)" onfocus="this.select()" onclick="event.stopPropagation()"></td>';}).join('')+'</tr>';}).join('');}
function onCell(inp){const i=parseInt(inp.dataset.i),c=inp.dataset.c,v=inp.value,old=S.rows[i][c];S.rows[i][c]=v;const lid=String(S.rows[i][C.id()]||'').trim();if(S.rowById[lid])S.rowById[lid][c]=v;if(c===C.est()){if(!S.sc[v])S.sc[v]=nextClr();const el=findEl(lid);if(el){setFill(el,S.sc[v]);el.dataset.est=v;}inp.style.background=S.sc[v];buildColors();buildSubColors();renderLegend();renderMiniKpis();renderDashboard();logActivity('edit','Estado modificado','Lote <b>'+lid+'</b>: <b>'+old+'</b> to <b>'+v+'</b>','a');}}
function fromTbl(e,lid){if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;closeTbl();switchView('map');setTimeout(()=>{const el=findEl(lid);if(el){openDP(lid,el);focusEl(el);}},150);}
function exportXL(){if(!S.rows.length)return;const ws=XLSX.utils.json_to_sheet(S.rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,'Lotes',ws);XLSX.writeFile(wb,'valora_lotes_'+new Date().toISOString().slice(0,10)+'.xlsx');logActivity('upload','Exportacion','Datos exportados <b>'+S.rows.length+'</b> lotes','b');}
function initFP(){const fp=$('fp'),hd=$('fpDrag');if(!fp||!hd)return;hd.addEventListener('mousedown',e=>{if(e.target.closest('button'))return;e.preventDefault();FPD={on:true,ox:e.clientX-fp.offsetLeft,oy:e.clientY-fp.offsetTop};document.body.style.userSelect='none';fp.style.transition='none';});window.addEventListener('mousemove',e=>{if(!FPD.on)return;const par=fp.offsetParent||document.body,mx=Math.max(0,par.offsetWidth-fp.offsetWidth),my=Math.max(0,par.offsetHeight-fp.offsetHeight);fp.style.left=clamp(e.clientX-FPD.ox,0,mx)+'px';fp.style.top=clamp(e.clientY-FPD.oy,0,my)+'px';});window.addEventListener('mouseup',()=>{if(!FPD.on)return;FPD.on=false;document.body.style.userSelect='';fp.style.transition='';});}
function toggleFP(){S.fpCol=!S.fpCol;const body=$('fpBody'),btn=$('fpColBtn');if(!body||!btn)return;body.style.display=S.fpCol?'none':'';btn.innerHTML=S.fpCol?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="12" height="12"><polyline points="9,18 15,12 9,6"/></svg>':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="12" height="12"><polyline points="15,18 9,12 15,6"/></svg>';}
function showLoader(msg){const l=$('loader');if(l){l.style.display='flex';const lt=$('loaderTxt');if(lt)lt.textContent=msg||'Procesando...';}}
function hideLoader(){const l=$('loader');if(l)l.style.display='none';}
function toast(msg,type){const ic=type==='ok'?'v ':type==='err'?'x ':'';const t=mk('div','toast'+(type==='ok'?' ok':type==='err'?' err':''));t.textContent=ic+msg;document.body.appendChild(t);requestAnimationFrame(()=>requestAnimationFrame(()=>t.classList.add('show')));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),200);},3000);}
try{applyTheme(localStorage.getItem('valora-theme')||'light');}catch(e){applyTheme('light');}
initLogos();initLoginCards();setupViewportEvents();initFP();